//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store_Online.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Store_Online.Resources.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage Management System.
        /// </summary>
        internal static string APP_NAME {
            get {
                return ResourceManager.GetString("APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string BTN_ADD {
            get {
                return ResourceManager.GetString("BTN_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BTN_CANCEL {
            get {
                return ResourceManager.GetString("BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string BTN_CLEAR {
            get {
                return ResourceManager.GetString("BTN_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string BTN_CLOSE {
            get {
                return ResourceManager.GetString("BTN_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string BTN_DELETE {
            get {
                return ResourceManager.GetString("BTN_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string BTN_EDIT {
            get {
                return ResourceManager.GetString("BTN_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string BTN_LOGIN {
            get {
                return ResourceManager.GetString("BTN_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string BTN_LOGOUT {
            get {
                return ResourceManager.GetString("BTN_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string BTN_NO {
            get {
                return ResourceManager.GetString("BTN_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string BTN_OK {
            get {
                return ResourceManager.GetString("BTN_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string BTN_REFRESH {
            get {
                return ResourceManager.GetString("BTN_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string BTN_SAVE {
            get {
                return ResourceManager.GetString("BTN_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string BTN_SEARCH {
            get {
                return ResourceManager.GetString("BTN_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string BTN_UPDATE {
            get {
                return ResourceManager.GetString("BTN_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string BTN_YES {
            get {
                return ResourceManager.GetString("BTN_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee.
        /// </summary>
        internal static string CATEGORY_COFFEE {
            get {
                return ResourceManager.GetString("CATEGORY_COFFEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drink.
        /// </summary>
        internal static string CATEGORY_DRINK {
            get {
                return ResourceManager.GetString("CATEGORY_DRINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERR_GENERAL {
            get {
                return ResourceManager.GetString("ERR_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string LBL_BRAND {
            get {
                return ResourceManager.GetString("LBL_BRAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chassis Number.
        /// </summary>
        internal static string LBL_CHASSIS_NUMBER {
            get {
                return ResourceManager.GetString("LBL_CHASSIS_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string LBL_COLOR {
            get {
                return ResourceManager.GetString("LBL_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Number.
        /// </summary>
        internal static string LBL_ENGINE_NUMBER {
            get {
                return ResourceManager.GetString("LBL_ENGINE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string LBL_FORGOT_PASSWORD {
            get {
                return ResourceManager.GetString("LBL_FORGOT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string LBL_LOADING {
            get {
                return ResourceManager.GetString("LBL_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string LBL_MODEL {
            get {
                return ResourceManager.GetString("LBL_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LBL_PASSWORD {
            get {
                return ResourceManager.GetString("LBL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Number.
        /// </summary>
        internal static string LBL_PLATE_NUMBER {
            get {
                return ResourceManager.GetString("LBL_PLATE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        internal static string LBL_REMEMBER_ME {
            get {
                return ResourceManager.GetString("LBL_REMEMBER_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string LBL_STATUS {
            get {
                return ResourceManager.GetString("LBL_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string LBL_USERNAME {
            get {
                return ResourceManager.GetString("LBL_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Back.
        /// </summary>
        internal static string LBL_WELCOME_BACK {
            get {
                return ResourceManager.GetString("LBL_WELCOME_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string LBL_YEAR {
            get {
                return ResourceManager.GetString("LBL_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking.
        /// </summary>
        internal static string MENU_BOOKING {
            get {
                return ResourceManager.GetString("MENU_BOOKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string MENU_CUSTOMER {
            get {
                return ResourceManager.GetString("MENU_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string MENU_DASHBOARD {
            get {
                return ResourceManager.GetString("MENU_DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string MENU_EMPLOYEE {
            get {
                return ResourceManager.GetString("MENU_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage.
        /// </summary>
        internal static string MENU_GARAGE {
            get {
                return ResourceManager.GetString("MENU_GARAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        internal static string MENU_INVOICE {
            get {
                return ResourceManager.GetString("MENU_INVOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS.
        /// </summary>
        internal static string MENU_POS {
            get {
                return ResourceManager.GetString("MENU_POS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        internal static string MENU_REPAIR {
            get {
                return ResourceManager.GetString("MENU_REPAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string MENU_REPORT {
            get {
                return ResourceManager.GetString("MENU_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string MENU_SETTING {
            get {
                return ResourceManager.GetString("MENU_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        internal static string MENU_VEHICLE {
            get {
                return ResourceManager.GetString("MENU_VEHICLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this record?.
        /// </summary>
        internal static string MSG_CONFIRM_DELETE {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data deleted successfully..
        /// </summary>
        internal static string MSG_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MSG_INFORMATION {
            get {
                return ResourceManager.GetString("MSG_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found..
        /// </summary>
        internal static string MSG_NO_DATA {
            get {
                return ResourceManager.GetString("MSG_NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved successfully..
        /// </summary>
        internal static string MSG_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string MSG_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data updated successfully..
        /// </summary>
        internal static string MSG_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MSG_WARNING {
            get {
                return ResourceManager.GetString("MSG_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS_Title.
        /// </summary>
        internal static string POS_TITLE {
            get {
                return ResourceManager.GetString("POS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        internal static string VAL_REQUIRED {
            get {
                return ResourceManager.GetString("VAL_REQUIRED", resourceCulture);
            }
        }
    }
}
